---
- name:  "Ansible 2.9+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.9', '>=')
    msg: "Required Ansible version is 2.9+ with include_tasks supporting tags"

- name: "install firewall"
  include_tasks:
    file: "firewall_install_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}_{{ firewall_rules_type }}.yml"
    apply:
      tags:
        - firewall
  tags:
    - firewall

- name: "configure firewall"
  include_tasks:
    file: "firewall_config_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}_{{ firewall_rules_type }}.yml"
    apply:
      tags:
        - firewall
        - firewall_config
        - config
  tags:
    - firewall
    - firewall_config
    - config

- name: "flush handlers"
  meta: flush_handlers
