---

- name: "install firewall"
  include_tasks: "firewall_install_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - firewall

- name: "configure firewall"
  include_tasks: "firewall_config_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
  tags:
    - firewall
    - firewall_config
    - config

- name: "flush handlers"
  meta: flush_handlers
