---
- name: "Debian version check ({{ ansible_distribution_major_version }})"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version is version('10','>=')
    msg: "Required version is 10+, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
    quiet: true

- name: "install firewall"
  when: firewall_do_install
  include_tasks:
    file: "firewall_install_iptables.yml"
    apply:
      tags:
        - firewall
  tags:
    - firewall

- name: "configure firewall"
  when: firewall_do_config
  include_tasks:
    file: "firewall_config_iptables.yml"
    apply:
      tags:
        - firewall
  tags:
    - firewall
