---

- import_tasks: firewall_install_Debian_9.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"
  tags:
    - firewall

- import_tasks: firewall_config_Debian_9.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "9"
  tags:
    - firewall
    - firewall_config
    - config

- import_tasks: firewall_install_Debian_10.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - firewall

- import_tasks: firewall_config_Debian_10.yml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "10"
  tags:
    - firewall
    - firewall_config
    - config
